import { cn } from '@/lib/utils'
import React from 'react'
import { Select } from './ui/select'
import GenericSelect from './generic/GenericSelect'
import Location from '../../public/location.json'
import { GenericComboBox } from './generic/GenericComboBox'

export default function Main() {
  // console.log(Location)

  const cities = [
    
      "Acampo",
      "Acton",
      "Adelanto",
      "Adin",
      "Aerial Acres",
      "Afton",
      "Agoura",
      "Agoura Hills",
      "Agua Dulce",
      "Aguanga",
      "Ahwahnee",
      "Alamo Oaks",
      "Alberhill",
      "Albion",
      "Alhambra",
      "Aliso Viejo",
      "Almanor",
      "Alpine",
      "Alpine Forest",
      "Alta Loma",
      "Altadena",
      "Alturas",
      "Amador City",
      "American Canyon",
      "Amsterdam",
      "Anaheim",
      "Anaheim Hills",
      "Anderson",
      "Angels Camp",
      "Angelus Oaks",
      "Angwin",
      "Annapolis",
      "Antelope",
      "Antelope Acres",
      "Antioch",
      "Anza",
      "Apache Junction",
      "Apple Valley",
      "Arbuckle",
      "Arcadia",
      "Arleta",
      "Arnold",
      "Arrowbear",
      "Arroyo Grande",
      "Artesia",
      "Artois",
      "Arvin",
      "Atascadero",
      "Athens",
      "Atwater",
      "Atwater Village",
      "Auberry",
      "Auburn",
      "Avalon",
      "Avenal",
      "Avila Beach",
      "Avondale",
      "Azusa",
      "Baker",
      "Bakersfield",
      "Baldwin Hills",
      "Baldwin Park",
      "Ballard",
      "Ballico",
      "Bangor",
      "Banning",
      "Bard",
      "Bardsdale",
      "Barstow",
      "Bass Lake",
      "Bassett",
      "Bay Point",
      "Bayliss",
      "Baywood Park",
      "Bear Reservoir",
      "Bear Valley",
      "Bear Valley Springs",
      "Beaumont",
      "Beckwourth",
      "Bel Air",
      "Belden",
      "Bell",
      "Bell Canyon",
      "Bell Gardens",
      "Bella Vista",
      "Bellflower",
      "Berkeley",
      "Bermuda Dunes",
      "Berry Creek",
      "Beverly Hills",
      "Big Bar",
      "Big Bear",
      "Big Bend",
      "Big Mountain Ridge",
      "Big Pines",
      "Big River",
      "Big Rock",
      "Biggs",
      "Biola",
      "Blairsden",
      "Bloomington",
      "Blue Jay",
      "Blue Lake",
      "Blythe",
      "Bodega",
      "Bodega Bay",
      "Bodfish",
      "Bombay Beach",
      "Bonadelle Ranchos",
      "Bonds Corner",
      "Bonita",
      "Bonsall",
      "Boonville",
      "Boron",
      "Borrego Springs",
      "Boulder City",
      "Boulevard",
      "Bradbury",
      "Brawley",
      "Brea",
      "Brentwood",
      "Brentwood (CC)",
      "Browns Valley",
      "Brownsville",
      "Brundage",
      "Brush Creek",
      "Buckhorn",
      "Buckingham Park",
      "Bucks Lake",
      "Buellton",
      "Buena Park",
      "Bullhead City",
      "Burbank",
      "Burlington",
      "Burney",
      "Burson",
      "Butte City",
      "Butte Meadows",
      "Butte Valley",
      "Butterfly Valley",
      "Buttonwillow",
      "Cabazon",
      "Cahuenga Pass",
      "Calabasas",
      "Calabasas Highlands",
      "Calabasas Park",
      "Caldors Corner",
      "Calexico",
      "Caliente",
      "California City",
      "Calimesa",
      "Calipatria",
      "Calistoga",
      "Calpella",
      "Calpine",
      "Camarillo",
      "Cambria",
      "Cameron Park",
      "Camino",
      "Campbellville",
      "Campo",
      "Camptonville",
      "Canby",
      "Canoga Park",
      "Cantil",
      "Canyon Areas",
      "Canyon Country",
      "Canyon Dam",
      "Canyon Lake",
      "Capay",
      "Carbondale",
      "Cardiff by the Sea",
      "Carefree",
      "Caribou",
      "Carlsbad",
      "Carmel Valley",
      "Carmichael",
      "Carnelian Bay",
      "Carpinteria",
      "Carson",
      "Carson City",
      "Caruthers",
      "Casa Conejo",
      "Cascade",
      "Casmalia",
      "Castaic",
      "Castellammare",
      "Castro Valley",
      "Cathedral City",
      "Catheys Valley",
      "Cayucos",
      "Cazadero",
      "Cedar Glen",
      "Cedarpines Park",
      "Ceres",
      "Cerritos",
      "Challenge",
      "Chandler",
      "Channel Islands",
      "Beach",
      "Charter Oak",
      "Chatsworth",
      "Cherokee",
      "Cherry Valley",
      "Chester",
      "Cheviot Hills",
      "Chico",
      "Chilcoot",
      "China Lake",
      "Chino",
      "Chino Hills",
      "Cholame",
      "Chowchilla",
      "Chula Vista",
      "Citrus Heights",
      "City Of Industry",
      "City Ranch",
      "City Terrace",
      "Clairemont Mesa",
      "Claremont",
      "Clear Creek",
      "Clearlake",
      "Clearlake Highlands",
      "Clearlake Oaks",
      "Clearlake Park",
      "Clio",
      "Clipper Mills",
      "Cloverdale",
      "Clovis",
      "Coachella",
      "Coalinga",
      "Coarsegold",
      "Cobb",
      "Coffee",
      "Cohasset",
      "Cold Springs",
      "College City",
      "Coloma",
      "Colton",
      "Colusa",
      "Commerce",
      "Compton",
      "Concord",
      "Concow",
      "Coolidge Springs",
      "Coos Bay",
      "Copperopolis",
      "Corcoran",
      "Cornell",
      "Corning",
      "Corona",
      "Corona del Mar",
      "Coronado",
      "Costa Mesa",
      "Cotati",
      "Coto de Caza",
      "Cottonwood",
      "Cottonwood Canyon",
      "Coulterville",
      "Country Club Park",
      "County - Los",
      "Angeles",
      "Covelo",
      "Covina",
      "Cowan Heights",
      "Crenshaw",
      "Crescent Mills",
      "Cressey",
      "Crestline",
      "Creston",
      "Cromberg",
      "Crows Landing",
      "Cudahy",
      "Cuesta By The Sea",
      "Culver City",
      "Cupertino",
      "Cutler",
      "Cuyama",
      "Cypress",
      "Cypress Park",
      "Dairyville",
      "Dales",
      "Dana Point",
      "Davis",
      "Dayton",
      "Del Cerro",
      "Del Kern",
      "Del Mar",
      "Del Rey",
      "Del Sur",
      "Delano",
      "Delevan",
      "Delhi",
      "Delleker",
      "Denair",
      "DeSabla",
      "Descanso",
      "Desert Center",
      "Desert Hot Springs",
      "Desert Lake",
      "Desert Shores",
      "Devore",
      "Di Giorgio",
      "Diamond Bar",
      "Diamond Springs",
      "Dillon Beach",
      "Dinuba",
      "Discovery Bay",
      "Dixie Valley",
      "Dixon",
      "Dobbins",
      "Dorris",
      "Dos Palos",
      "Douglas City",
      "Dove Canyon",
      "Downey",
      "Downieville",
      "Doyle",
      "Drytown",
      "Duarte",
      "Dublin",
      "Dulzura",
      "Dunnigan",
      "Dunsmuir",
      "Durham",
      "Eagle Park",
      "Eagle Rock",
      "East Bakersfield",
      "East Gridley",
      "East Los Angeles",
      "East San Diego",
      "Eastvale",
      "Echo Park",
      "Edison",
      "Edward",
      "Edwards",
      "El Cajon",
      "El Camino",
      "El Centro",
      "El Cerrito",
      "El Cerrito (CC)",
      "El Dorado",
      "El Dorado Hills",
      "El Mirage",
      "El Monte",
      "El Nido",
      "El Portal",
      "El Porto",
      "El Rio",
      "El Segundo",
      "El Sereno",
      "El Sobrante",
      "Elk Creek",
      "Elk Grove",
      "Empire",
      "Encinitas",
      "Encino",
      "Escalon",
      "Escondido",
      "Esparto",
      "Estrella",
      "Eureka",
      "Exeter",
      "Fair Oaks Ranch",
      "Fair Play",
      "Fairfield",
      "Fairmead",
      "Fairmont",
      "Fallbrook",
      "Falling Springs",
      "Faria Beach",
      "Farmersville",
      "Fawnskin",
      "Feather Falls",
      "Felicity",
      "Fellows",
      "Fernwood",
      "Fiddletown",
      "Fillmore",
      "Finley",
      "Firebaugh",
      "Fish Camp",
      "Flagstaff",
      "Florence",
      "Flournoy",
      "Folsom",
      "Fontana",
      "Foothill Ranch",
      "Forbestown",
      "Foreign Country",
      "Forest Falls",
      "Forest Ranch",
      "Foresthill",
      "Forestville",
      "Forrest Park",
      "Fort Bragg",
      "Foster City",
      "Fountain Valley",
      "Four Corners",
      "Four Points",
      "Fowler",
      "Fox Hills",
      "Frazier Park",
      "Fremont",
      "Fremont Valley",
      "French Camp",
      "French Gulch",
      "French Valley",
      "Frenchtown",
      "Fresno",
      "Friant",
      "Fruitvale",
      "Fruto",
      "Fullerton",
      "Galt",
      "Garden Grove",
      "Garden Valley",
      "Gardena",
      "Garey",
      "Garlock",
      "Garner Valley",
      "Garnet",
      "Garvanza",
      "Gaviota",
      "Genesee",
      "Georgetown",
      "Gerber",
      "Gilbert",
      "Gilroy",
      "Glassell Park",
      "Glen Avon",
      "Glen Helen",
      "Glen Ivy",
      "Glenbrook",
      "Glencoe",
      "Glendale",
      "Glendora",
      "Glenhaven",
      "Glenn",
      "Glennville",
      "Glenview",
      "Golden Hills",
      "Goleta",
      "Good Hope",
      "Goodyears Bar",
      "Gorman",
      "Graeagle",
      "Granada Hills",
      "Grand Terrace",
      "Grapevine",
      "Grass Valley",
      "Greeley",
      "Greeley Hill",
      "Green Valley",
      "Green Valley Lake",
      "Greenacres",
      "Greenville",
      "Gridley",
      "Grizzly Flats",
      "Groveland",
      "Grover Beach",
      "Guadalupe",
      "Gualala",
      "Guatay",
      "Guerneville",
      "Guinda",
      "Gustine",
      "Hacienda Hts",
      "Hallelujah Junction",
      "Hamilton Branch",
      "Hamilton City",
      "Hancock Park",
      "Hanford",
      "Harbor City",
      "Harmony",
      "Havasu City",
      "Havilah",
      "Hawaiian Gardens",
      "Hawthorne",
      "Hayfork",
      "Hayward",
      "Healdsburg",
      "Heber",
      "Helendale",
      "Hemet",
      "Henderson",
      "Herald",
      "Herlong",
      "Hermosa Beach",
      "Hesperia",
      "Hidden Hills",
      "Hidden Valley",
      "Hidden Valley Lake",
      "Highgrove",
      "Highland",
      "Highland Park",
      "Highland Springs",
      "Hillcrest Center",
      "Hilltop",
      "Hilmar",
      "Hollister",
      "Hollydale",
      "Hollywood",
      "Hollywood Hills",
      "Hollywood Hills East",
      "Holtville",
      "Homeland",
      "Homewood",
      "Honcut",
      "Honolulu",
      "Hooker",
      "Hopland",
      "Hornbrook",
      "Hornitos",
      "Horse Creek",
      "Hughson",
      "Huntington Beach",
      "Huntington Park",
      "Huron",
      "Hyde Park",
      "Idyllwild",
      "Igo",
      "Imperial",
      "Imperial Beach",
      "Imperial City",
      "Incline Village",
      "Indian Falls",
      "Indian Hills",
      "Indian Springs",
      "Indian Valley",
      "Indian Wells",
      "Indio",
      "Inglewood",
      "Inskip",
      "Inyokern",
      "Ione",
      "Irvine",
      "Irwindale",
      "Isla Vista",
      "Isleton",
      "Ivanhoe",
      "Jackson",
      "Jacumba",
      "Jamestown",
      "Jamul",
      "Janesville",
      "Jefferson Park",
      "Johannesburg",
      "Johnson Valley",
      "Johnsville",
      "Jonesville",
      "Joshua Hills",
      "Joshua Tree",
      "Julian",
      "Juniper Flats",
      "Juniper Hills",
      "Jupiter",
      "Kagel Canyon",
      "Keddie",
      "Keene",
      "Kelsey",
      "Kelseyville",
      "Kerman",
      "Kernville",
      "Keswick",
      "Keyes",
      "Kings Beach",
      "Kingsburg",
      "Kirkwood",
      "Knights Landing",
      "Komandorski Village",
      "Kramer Junction",
      "La Canada Flintridge",
      "La Conchita",
      "La Crescenta",
      "La Grange",
      "La Habra",
      "La Habra Heights",
      "La Jolla",
      "La Mesa",
      "La Mirada",
      "La Palma",
      "La Porte",
      "La Puente",
      "La Quinta",
      "La Sierra",
      "La Tuna Canyon",
      "La Verne",
      "Ladera Heights",
      "Ladera Ranch",
      "Lafayette",
      "Laguna Beach",
      "Laguna Hills",
      "Laguna Niguel",
      "Laguna Woods",
      "Lake Almanor",
      "Lake Almanor Peninsula",
      "Lake Almanor West",
      "Lake Arrowhead",
      "Lake Balboa",
      "Lake Camanche",
      "Lake Don Pedro",
      "Lake Elizabeth",
      "Lake Elsinore",
      "Lake Forest",
      "Lake Havasu",
      "Lake Hollywood",
      "Lake Hughes",
      "Lake Isabella",
      "Lake Los Angeles",
      "Lake Mathews",
      "Lake Nacimiento",
      "Lake Sherwood",
      "Lakehead",
      "Lakeport",
      "Lakeside",
      "Lakeview",
      "Lakeview Terrace",
      "Lakewood",
      "Lamont",
      "Lancaster",
      "Landers",
      "Lang",
      "LaPorte",
      "Las Vegas",
      "Lathrop",
      "Laton",
      "Laughlin",
      "Lawndale",
      "Laytonville",
      "Le Grand",
      "Lebec",
      "Leggett",
      "Leimert Park",
      "Lemon Grove",
      "Lemoore",
      "Lennox",
      "Leona Valley",
      "Lincoln Heights",
      "Linda",
      "Linda Vista",
      "Linden",
      "Lindsay",
      "Litchfield",
      "Little Rock",
      "Live Oak",
      "Livermore",
      "Livingston",
      "Llano",
      "Loch Lomond",
      "Lockeford",
      "Lodi",
      "Lodoga",
      "Logan Heights",
      "Loma Linda",
      "Loma Rica",
      "Lomita",
      "Lomo",
      "Lompoc",
      "Long Barn",
      "Long Beach",
      "Longview",
      "Lookout",
      "Loraine",
      "Los Alamitos",
      "Los Alamos",
      "Los Altos",
      "Los Angeles",
      "Los Banos",
      "Los Feliz",
      "Los Molinos",
      "Los Nietos",
      "Los Olivos",
      "Los Osos",
      "Lost City",
      "Lost Hills",
      "Lotus",
      "City List By Alphabetical Order (continued on next page)",
      "Page 2",
      "CRMLS© Updated 5/24/11 V5.5A",
      "Lower Lake",
      "Loyalton",
      "Lucerne",
      "Lucerne Valley",
      "Lynwood",
      "Lytle Creek",
      "Macdoel",
      "Madeline",
      "Madera",
      "Madera Acres",
      "Madera Ranchos",
      "Magalia",
      "Malibu",
      "Mammoth Lakes",
      "Manhattan Beach",
      "Manteca",
      "Manton",
      "Mar Vista",
      "Maricopa",
      "Marina",
      "Marina del Rey",
      "Mariposa",
      "Martell",
      "Marysville",
      "Maxwell",
      "Maybe",
      "Mayfair",
      "Maywood",
      "McCloud",
      "Mcfarland",
      "Mckittrick",
      "Mead Valley",
      "Meadow Valley",
      "Meadowbrook",
      "Meadows Field",
      "Mecca",
      "Meiners Oaks",
      "Mendocino",
      "Mendota",
      "Menifee",
      "Mentone",
      "Merced",
      "Merced Falls",
      "Meridian",
      "Mesa",
      "Mettler",
      "Middleton",
      "Middletown",
      "Midpines",
      "Midway City",
      "Milford",
      "Mill Creek",
      "Mill Valley",
      "Millville",
      "Mineral",
      "Mint Canyon",
      "Mira Loma",
      "Mira Mesa",
      "Mira Monte",
      "Miraleste",
      "Miramar",
      "Miramonte",
      "Mission Hills (San",
      "Diego)",
      "Mission Hills (San",
      "Fernando)",
      "Mission Hills Santa",
      "Barbara",
      "Mission Valley",
      "Mission Viejo",
      "Modesto",
      "Modjeska Canyon",
      "Mohawk",
      "Mojave",
      "Mokelumne Hill",
      "Moneta",
      "Monolith",
      "Monrovia",
      "Montague",
      "Montclair",
      "Monte Nido",
      "Montebello",
      "Montecito",
      "Montecito Heights",
      "Monterey Hills",
      "Monterey Park",
      "Montpelier",
      "Montrose",
      "Moorpark",
      "Moreno Valley",
      "Morgan Hill",
      "Morningside Park",
      "Morongo Valley",
      "Morro Bay",
      "Mount Aukum",
      "Mount Laguna",
      "Mount Olympus",
      "Mount Signal",
      "Mount Washington",
      "Mountain Center",
      "Mountain Home",
      "Village",
      "Mountain Mesa",
      "Mountain Ranch",
      "Mountain Valley",
      "Mt Baldy",
      "Murphys",
      "Murrieta",
      "Napa",
      "National City",
      "Needles",
      "Neenach",
      "Nelson",
      "Nevada",
      "Nevada City",
      "New Auberry",
      "Newberry Springs",
      "Newbury Park",
      "Newhall",
      "Newman",
      "Newport Beach",
      "Newport Coast",
      "Nice",
      "Nicolaus",
      "Niland",
      "Nipomo",
      "Norco",
      "Nord",
      "North Edwards",
      "North Fork",
      "North Highlands",
      "North Hills",
      "North Hollywood",
      "North Las Vegas",
      "North Park (San",
      "Diego)",
      "North Shore",
      "North Tustin",
      "North Wawona",
      "Northridge",
      "Norwalk",
      "Norwood Village",
      "Novato",
      "Nuevo/Lakeview",
      "Oak Glen",
      "Oak Hills",
      "Oak Park",
      "Oak Run",
      "Oak View",
      "Oakdale",
      "Oakhurst",
      "Oakland",
      "Oakley",
      "Oaks",
      "Oasis",
      "Oban",
      "Ocean Beach (San",
      "Diego)",
      "Ocean Park",
      "Oceano",
      "Oceanside",
      "Ocotillo",
      "Oildale",
      "Ojai",
      "Olancha",
      "Old Canyon",
      "Old Forbestown",
      "Old Station",
      "Old Town (San",
      "Diego)",
      "Olive",
      "Olive View",
      "Olivehurst",
      "Olympia",
      "Olympic Village",
      "Omo Ranch",
      "O’Neals",
      "Ono",
      "Ontario",
      "Onyx",
      "Orange",
      "Orange Cove",
      "Orange Park Acres",
      "Orangevale",
      "Orcutt",
      "Oregon House",
      "Orland",
      "Orosi",
      "Oroville",
      "Ortega Mountain",
      "Otay Mesa",
      "Oxnard",
      "Pacific Beach (San",
      "Diego)",
      "Pacific Grove",
      "Pacific Palisades",
      "Pacifica",
      "Pacoima",
      "Pahrump",
      "Pala",
      "Palermo",
      "Palisades Heights",
      "Palm Desert",
      "Palm Springs",
      "Palmdale",
      "Palms",
      "Palo Cedro",
      "Palo Verde",
      "Paloma",
      "Palomar Mountain",
      "Palos Verdes Estates",
      "Palos Verdes Peninsula - Unincorporated",
      "Panorama City",
      "Paradise",
      "Paradise Hills",
      "Paramount",
      "Park Hills Heights",
      "Parker",
      "Parklabrea",
      "Parlier",
      "Pasadena",
      "Paskenta",
      "Paso Robles",
      "Patterson",
      "Pauma Valley",
      "Paxton",
      "Paynes Creek",
      "Pearblossom",
      "Pearland",
      "Pearsonville",
      "Pebble Beach",
      "Pedley",
      "Penn Valley",
      "Penngrove",
      "Peoria",
      "Perris",
      "Petaluma",
      "Phelan",
      "Phillips Ranch",
      "Phoenix",
      "Pico",
      "Pico Rivera",
      "Pike",
      "Pine Cove",
      "Pine Grove",
      "Pine Mountain",
      "Pine Valley",
      "Pinedale",
      "Pinetree",
      "Pinole",
      "Pinon Hills",
      "Pinyon Pines",
      "Pioneer",
      "Pioneertown",
      "Piru",
      "Pismo Beach",
      "Pittsburg",
      "Placentia",
      "Placerville",
      "Plainsburg",
      "Planada",
      "Platina",
      "Playa del Rey",
      "Playa Vista",
      "Plymouth",
      "Point Dume",
      "Point Loma",
      "Point Mugu",
      "Pollock Pines",
      "Pomona",
      "Pond",
      "Pope Valley",
      "Port Hueneme",
      "Porterville",
      "Portola",
      "Portola Hills",
      "Potrero",
      "Potter Valley",
      "Poway",
      "Pozo",
      "Prather",
      "Prattville",
      "Prescott",
      "Princeton",
      "Proberta",
      "Pumpkin Center",
      "Quail Valley",
      "Quartz Hill",
      "Quincy",
      "Rackerby",
      "Rail Road Flat",
      "Rainbow",
      "Ramona",
      "Ranchita",
      "Rancho Bernardo",
      "(San Diego)",
      "Rancho California",
      "Rancho Cordova",
      "Rancho Cucamonga",
      "Rancho Dominguez",
      "Rancho Mirage",
      "Rancho Murieta",
      "Rancho Palos",
      "Verdes",
      "Rancho Park",
      "Rancho Penasquitos",
      "Rancho Santa Fe",
      "Rancho Santa",
      "Margarita",
      "Rancho Tehama",
      "Reserve",
      "Rancho Vista",
      "Randsburg",
      "Ravendale",
      "Ravenna",
      "Raymond",
      "Red Bank",
      "Red Bluff",
      "Redding",
      "Redlands",
      "Redman",
      "Redondo Beach",
      "Redwood City",
      "Redwood Valley",
      "Reedley",
      "Reno",
      "Reseda",
      "Rialto",
      "Rich Bar",
      "Richfield",
      "Richvale",
      "Ridgecrest",
      "Rimforest",
      "Rio Linda",
      "Ripon",
      "Ritter Ranch",
      "River Kern",
      "River Pines",
      "Riverbank",
      "Riverdale",
      "Riverside",
      "Riviera",
      "Robbins",
      "Robinson Mills",
      "Robinsons Corner",
      "Rocklin",
      "Rohnert Park",
      "Rolling Hills",
      "Rolling Hills Estates",
      "Romoland",
      "Romona",
      "Roosevelt",
      "Rosamond",
      "Rose Park",
      "Rosemead",
      "Roseville",
      "Rosewood",
      "Rossmoor",
      "Rough and Ready",
      "Round Mountain",
      "Rowland Heights",
      "Rubidoux",
      "Running Springs",
      "Area",
      "Ruth",
      "Sacramento",
      "Sage",
      "Salida",
      "Salinas",
      "Salton City",
      "Salton Sea",
      "Salton Sea Beach",
      "San Andreas",
      "San Bernardino",
      "San Buenaventura",
      "San Carlos",
      "San Clemente",
      "San Diego",
      "San Dimas",
      "San Fernando",
      "San Francisco",
      "San Gabriel",
      "San Geronimo",
      "San Jacinto",
      "San Joaquin",
      "San Jose",
      "San Juan Capistrano",
      "San Leandro",
      "San Luis Obispo",
      "San Luis Rey",
      "San Marcos",
      "San Marino",
      "San Miguel",
      "San Pablo",
      "San Pedro",
      "San Rafael",
      "San Ramon",
      "San Simeon",
      "San Ysidro",
      "Sandberg",
      "Sanger",
      "Santa Ana",
      "Santa Ana Heights",
      "Santa Barbara",
      "Santa Clarita",
      "Santa Cruz",
      "Santa Fe Springs",
      "Santa Margarita",
      "Santa Maria",
      "Santa Monica",
      "Santa Nella",
      "Santa Paula",
      "Santa Rosa",
      "Santa Rosa (SON)",
      "Santa Ynez",
      "Santa Ysabel",
      "Santee",
      "Saratoga Springs",
      "Saticoy",
      "Saugus",
      "Sawtelle",
      "Scotts Valley",
      "Scottsdale",
      "Scripps Miramar",
      "Seal Beach",
      "Sebastopol",
      "Sedco",
      "Sedona",
      "Seeley",
      "Selma",
      "Seneca",
      "Sequim",
      "Shadow Hills",
      "Shafter",
      "Shandon",
      "Shasta",
      "Shasta Lake",
      "Shaver Lake",
      "Shelter Cove",
      "Sherman Oaks",
      "Shingle Springs",
      "Shingletown",
      "Sierra City",
      "Sierra Madre",
      "Sierraville",
      "Signal Hill",
      "Silver Lake",
      "Silverado Canyon",
      "Simi Valley",
      "Simmler",
      "Sisquoc",
      "Sky Valley",
      "Sleepy Valley",
      "Sloat",
      "Sloughhouse",
      "Smartsville",
      "Smoke Tree Valley",
      "Snelling",
      "Soda Bay",
      "Solana Beach",
      "Soledad",
      "Solvang",
      "Somerset",
      "Somis",
      "Sonoma",
      "Sonora",
      "Sorrento",
      "South Dos Palos",
      "South El Monte",
      "South Gate",
      "South Lake Tahoe",
      "South Pasadena",
      "South San Francisco",
      "South San Gabriel",
      "South San Jose Hills",
      "South Yuba",
      "Sparks",
      "Spring Garden",
      "Spring Valley",
      "Springville",
      "Squaw Valley",
      "St. Helena",
      "Stallion Springs",
      "Standish",
      "Stanton",
      "Stateline",
      "Stevenson Ranch",
      "Stevinson",
      "Stirling City",
      "Stockdale",
      "Stockton",
      "Stonyford",
      "Storrie",
      "Strawberry",
      "Strawberry Valley",
      "Studio City",
      "Sugar Loaf",
      "Sulpher Springs",
      "Summerland",
      "Sun City",
      "Sun Valley",
      "Sun Village",
      "Sunland",
      "Sunnybrook",
      "Sunnymead",
      "Sunset Beach",
      "Surf",
      "Surfside",
      "Surprise",
      "Susanville",
      "Sutter",
      "Sutter Creek",
      "Sutter Hill",
      "Sylmar",
      "Sylvia Park",
      "Taft",
      "Tahoe City",
      "Tahoe Vista",
      "Tahoma",
      "Tarzana",
      "Taylorsville",
      "Tecate",
      "Tehachapi",
      "Tehama",
      "Temecula",
      "Tempe",
      "Temple City",
      "Templeton",
      "Termo",
      "Thermal",
      "Thermalito",
      "Thornton",
      "Thousand Oaks",
      "Thousand Palms",
      "Tierrasanta",
      "Tobin",
      "Tollhouse",
      "Toluca Lake",
      "Topanga",
      "Topanga Park",
      "Torrance",
      "Trabuco Canyon",
      "Tracy",
      "Traver",
      "Trigo",
      "Trinity Center",
      "Trona",
      "Tropico Village",
      "Trousdale Estates",
      "Truckee",
      "Tucson",
      "Tujunga",
      "Tulare",
      "Tupman",
      "Turlock",
      "Tustin",
      "Tuttletown",
      "Twain",
      "Twain Harte",
      "Twin Peaks",
      "Ukiah",
      "Union City",
      "Universal City",
      "University City",
      "Upland",
      "Upper Lake",
      "Vacaville",
      "Val Verde Park",
      "Valencia",
      "Valinda",
      "Vallecito",
      "Vallejo",
      "Valley Center",
      "Valley Glen",
      "Valley Springs",
      "Valley Village",
      "Valyermo",
      "Van Nuys",
      "Vandenburg Village",
      "Vasquez Rocks",
      "Venice",
      "Ventura",
      "Verdi",
      "Verdugo City",
      "Vernon",
      "Victor Valley",
      "Victorville",
      "View Park",
      "Villa Park",
      "Vina",
      "Vinton",
      "Viola",
      "Virgilia",
      "Visalia",
      "Vista",
      "Vista Park",
      "Volcano",
      "Wallace",
      "Walnut",
      "Walnut Park",
      "Warner Springs",
      "Wasco",
      "Waterford",
      "Wawona",
      "Weaverville",
      "Weed",
      "Weldon",
      "West Covina",
      "West Hills",
      "West Hollywood",
      "West Los Angeles",
      "West Point",
      "Westchester",
      "Westlake Village",
      "Westminster",
      "Westmorland",
      "Westwood",
      "Westwood - Century",
      "City",
      "Wheatland",
      "Whiskeytown",
      "Whispering Pines",
      "Whitely Gardens",
      "Whitewater",
      "Whitmore",
      "Whittier",
      "Wilcox Valley",
      "Wilderville",
      "Wildomar",
      "Wildwood",
      "Williams",
      "Willits",
      "Willow Creek",
      "Willow Springs",
      "Willowbrook",
      "Willows",
      "Wilmington",
      "Wilseyville",
      "Wilson Valley",
      "Wilsona Gardens",
      "Wilton",
      "Winchester",
      "Windsor",
      "Windsor Hills",
      "Winnetka",
      "Winterhaven",
      "Winton",
      "Wishon",
      "Wofford Heights",
      "Wonder Valley",
      "Woodcrest",
      "Woodlake",
      "Woodland Hills",
      "Woodside Village",
      "Woody",
      "Wrightwood",
      "Wyandotte",
      "Yankee Hill",
      "Yorba Linda",
      "Yorkville",
      "Yosemite",
      "Yreka",
      "Yuba City",
      "Yucaipa",
      "Yucca Valley",
      "Yuma",
      "Zephyr Cove",
      "Unincorporated",
      "Unknown",
      "Outside Area -",
      "(Inside CA)",
      "Outside Area -",
      "(Outside CA)"
    
  ];
  
  const cityObjects = cities.map(city => {
    return { "value": city, "label": city };
  });
  
  console.log(cityObjects);
  return (
    <div className={cn("flex ml-48 mr-48 mt-20 ")}>
      <div className={cn(" flex-[1] ")}>

        <div>
          {/* <GenericSelect placeholder='Location' data={Location}/> */}
          <GenericComboBox data={Location} title='Location'/>
        </div>


      </div>


      <div  className={cn(" flex-[3]")}>




      </div>



    </div>
  )
}
